### PR TITLE
Add KMS_MIN_PORT and KMS_MAX_PORT env vars

### PR DESCRIPTION
**Pull request by whitphx**
Hello.
This change enables to configure `minPort` and `maxPort` via env vars.

### CODE REVIEW

**Review by j1elo — APPROVED** [review]

**Comment by j1elo** [comment]
Change looks good, I will merge as soon as I can write docs for the Docker overview page

**Comment by whitphx** [comment]
@j1elo Thank you very much. Shall I also edit the doc if possible?
If so, can you tell me where it is?

**Comment by j1elo** [comment]
Don't worry; the doc is edited in the Docker Hub page itself, so you
would need admin permissions. It's a short description so I'll be able
to have it for next week.

**Comment by whitphx** [comment]
I see, thanks!

**Comment by whitphx** [comment]
@j1elo Thank you for merging the PR.
However, it seems the docker image on DockerHub has not included the change.
When will it be, or is something needed to use it?

**Comment by j1elo** [comment]
Hi, the nightly images were correctly updated, make sure you have always pulled the latest version:

```
docker pull kurento/kurento-media-server-dev:latest
docker run -ti --rm --entrypoint /bin/bash kurento/kurento-media-server-dev:latest -c 'grep KMS_MIN_PORT entrypoint.sh'

>    if [[ -n "${KMS_MIN_PORT:-}" ]]; then
>        set_parameter "$BASE_RTP_FILE" "minPort" "$KMS_MIN_PORT"
```

The new feature will ship on next release, no definitive date for that but I'd guesstimate that around this month

**Comment by micaelgallego** [comment]
Note that changes are available in kurento/kurento-media-server-dev:latest image until next release.

**Comment by whitphx** [comment]
Thank you both!

Oh, I didn't see the nightly build (kurento/kurento-media-server-dev) repository.
https://hub.docker.com/r/kurento/kurento-media-server-dev 😄 

And thank you for guessing the next release time too.

**Pull request merged**
