### PR TITLE
Change version of Ubuntu:

### PR DESCRIPTION
**Pull request by alersrt**
- install the Kurento media server on Ubuntu 16.04

### CODE REVIEW

**Comment by tyranron** [comment]
I'm interested in this one too.

@nordri ping

**Comment by nordri** [comment]
Hello there,
Why don't you use this one?:
https://github.com/Kurento/kurento-docker/blob/master/docker/Dockerfile.xenial

**Comment by tyranron** [comment]
@nordri could you point us to Docker Hub image for `xenial`? I can only find [this one](https://hub.docker.com/r/fiware/stream-oriented-kurento/~/dockerfile/) which is `trusty`.

**Comment by nordri** [comment]
OK guys, sorry for the delay. As you may know, kurento team was hired by Twilio and the rest of us are quite busy with another projects.
We've created new Docker images for the new version on Xenial as on Trusty.
You can find them in our Docker Hub repo. 
https://hub.docker.com/r/kurento/kurento-media-server/
Thanks

**Comment by tyranron** [comment]
@nordri oh, thanks! That's exactly we're looking for! ❤️

cc @alersrt

**Comment by alersrt** [comment]
@nordri very thanks! It is good news!

**Pull request closed without merging**
