### PR TITLE
Feature/add support for rsa ecdsa cert params

### PR DESCRIPTION
**Pull request by sebawagner**
## What is the current behavior you want to change?

- Currently you can't configure RSA and ECDSA certificates via docker parameters. Kurento has parameters but the entry script doesn't expose them
- Those parameters are required if multiple KMS servers are used within same browser. Firefox requires all KMS to have the same certificate, see also Kurento docs: https://doc-kurento.readthedocs.io/en/latest/features/security.html#media-plane-security-dtls

There isn't currently a way to configure those parameters if you run via Docker. Other then customising the DockerFile. And trying to rebuild your own image.

## What is the new behavior provided by this change?

Ability to pass in RSA and ECDSA certificate. Adds 2 new parameters:
 - KMS_PEM_CERTIFICATE_RSA - Set pemCertificateRSA to Path to RSA certificate
 - KMS_PEM_CERTIFICATE_ECDSA - Set pemCertificateECDSA to Path to ECDSA certificate

There is a minor change to the set_parameter function in the script: Changing to use "|" as delimiter as opposed to "/" as delimiter as you can't otherwise "regex replace" a variable that has "/" inside the part you want to replace.

Example docker command to mount certificate + pass in to parameters:
`docker run -d --v /my/path/locally/essential-cert-kurento.pem:/etc/kurento/modules/kurento/essential-cert-kurento.pem --env KMS_PEM_CERTIFICATE_RSA=/etc/kurento/modules/kurento/essential-cert-kurento.pem -p 5555:8888 kurento/kurento-media-server`

## How has this been tested?
 - Run and install both RSA and ECDSA certificate and have 2 KMS nodes runnings.
 - Testing with both Chrome and Firefox. 
 - Making sure that Firefox connects to both KMS and receives as well as streams video

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature / enhancement (non-breaking change which improves the project)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] My change requires a change to the documentation
- [ ] My change requires a change in other repository 

A new section in the documentation to document those parameters at: https://doc-kurento.readthedocs.io/en/latest/user/configuration.html might be useful.

## Checklist

- [x] I have read the Contribution Guidelines 
- [x] I have added an explanation of what the changes do and why they should be included
- [ ] I have written new tests for the changes, as applicable, and have successfully run them locally

No new tests, just manual testing as its simply adding ability to pass in ENV variables.

### CODE REVIEW

**Comment by sebawagner** [comment]
Any chance this PR could be reviewed? 
It feels like a minor change. But then maybe there is a better way of achieving the same.

**Comment by j1elo** [comment]
On 14/08/2021 05.51, Sebastian Wagner wrote:
>
> Any chance this PR could be reviewed?
> It feels like a minor change. But then maybe there is a better way of
> achieving the same.
>

It's a minor addition and I'll gladly review and add it to the Docker
images; but you'll have to be patient, we're on holidays :)

**Comment by sebawagner** [comment]
Cool thanks!

**Comment by sebawagner** [comment]
Hi! Any chance this could be merged? 
Unfortunate building your own image seems difficult, last time I tried building this image failed because some repositories no more being public.

**Comment by j1elo** [comment]
Thanks for the patience! I've reviewed it and seems perfectly fine for me.

In principle I don't think that changing from `/` to `|` as separator in the *sed* command will cause any issues.

Docs added in https://github.com/Kurento/doc-kurento/commit/bb545b99fc0f8af9f6cb7d5edd71479e9d430d49

Thanks!

**Comment by sebawagner** [comment]
Thx!

**Pull request merged**
