### PR TITLE
STUN server configuration information in README.md

### PR DESCRIPTION
**Pull request by JanuszP**
When deploying to remote server it doesn't work out of the box. There is no information on STUN server configuration. Added that to documentation. What do you think?

### CODE REVIEW

**Comment by callmephilip** [comment]
+1

**Comment by valanz** [comment]
👍

**Comment by samuel-allan** [comment]
This should def. be merged.

**Comment by kshmidt** [comment]
Seems like this configuration is not actual anymore because of 1e43853

**Comment by j1elo** [comment]
All usage information for KMS Docker images was moved to the Docker Hub page. This README has been rewritten to homogeneize with that of kurento-media-server repository; it also now points to the correct page in Docker Hub.

**Pull request closed without merging**
